# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'LoginUI2.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Login")
        Dialog.resize(266, 224)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Dialog.sizePolicy().hasHeightForWidth())
        Dialog.setSizePolicy(sizePolicy)
        self.verticalLayout = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.tabWidget = QtWidgets.QTabWidget(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabWidget.sizePolicy().hasHeightForWidth())
        self.tabWidget.setSizePolicy(sizePolicy)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.tab)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_7 = QtWidgets.QLabel(self.tab)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.verticalLayout_3.addWidget(self.label_7)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.label_2 = QtWidgets.QLabel(self.tab)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 2, 0, 1, 1)

        self.PASSWORD_LineEdit = QtWidgets.QLineEdit(self.tab)
        self.PASSWORD_LineEdit.setObjectName("PASSWORD_LineEdit")
        self.PASSWORD_LineEdit.setEchoMode(QtWidgets.QLineEdit.Password)
        
        self.gridLayout.addWidget(self.PASSWORD_LineEdit, 2, 1, 1, 1)
        self.label = QtWidgets.QLabel(self.tab)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.USERNAME_LineEdit = QtWidgets.QLineEdit(self.tab)
        self.USERNAME_LineEdit.setObjectName("USERNAME_LineEdit")
        self.gridLayout.addWidget(self.USERNAME_LineEdit, 0, 1, 1, 1)
        self.verticalLayout_3.addLayout(self.gridLayout)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem)
        self.SubmitButton = QtWidgets.QPushButton(self.tab)
        self.SubmitButton.setObjectName("SubmitButton")
        self.verticalLayout_3.addWidget(self.SubmitButton)
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.tab_2)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_6 = QtWidgets.QLabel(self.tab_2)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.verticalLayout_2.addWidget(self.label_6)
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_3 = QtWidgets.QLabel(self.tab_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.gridLayout_2.addWidget(self.label_3, 0, 0, 1, 1)


        self.NewPassword_LineEdit = QtWidgets.QLineEdit(self.tab_2)
        self.NewPassword_LineEdit.setObjectName("NewPassword_LineEdit")
        self.NewPassword_LineEdit.setEchoMode(QtWidgets.QLineEdit.Password)

        self.gridLayout_2.addWidget(self.NewPassword_LineEdit, 1, 2, 1, 1)
        self.NewUser_LineEdit = QtWidgets.QLineEdit(self.tab_2)
        self.NewUser_LineEdit.setObjectName("NewUser_LineEdit")
        self.gridLayout_2.addWidget(self.NewUser_LineEdit, 0, 2, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.tab_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.gridLayout_2.addWidget(self.label_5, 2, 0, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.tab_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.gridLayout_2.addWidget(self.label_4, 1, 0, 1, 1)

        self.ConfirmPassword_LineEdit = QtWidgets.QLineEdit(self.tab_2)
        self.ConfirmPassword_LineEdit.setObjectName("ConfirmPassword_LineEdit")
        self.ConfirmPassword_LineEdit.setEchoMode(QtWidgets.QLineEdit.Password)

        self.gridLayout_2.addWidget(self.ConfirmPassword_LineEdit, 2, 2, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.tab_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.gridLayout_2.addWidget(self.label_8, 3, 0, 1, 1)


        self.AdminPassword_LineEdit = QtWidgets.QLineEdit(self.tab_2)
        self.AdminPassword_LineEdit.setObjectName("AdminPassword_LineEdit")
        self.AdminPassword_LineEdit.setEchoMode(QtWidgets.QLineEdit.Password)


        self.gridLayout_2.addWidget(self.AdminPassword_LineEdit, 3, 2, 1, 1)
        self.verticalLayout_2.addLayout(self.gridLayout_2)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem1)
        self.AddButton = QtWidgets.QPushButton(self.tab_2)
        self.AddButton.setObjectName("AddButton")
        self.verticalLayout_2.addWidget(self.AddButton)
        self.tabWidget.addTab(self.tab_2, "")
        self.verticalLayout.addWidget(self.tabWidget)

        self.retranslateUi(Dialog)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label_7.setText(_translate("Dialog", "Login"))
        self.label_2.setText(_translate("Dialog", "Password:"))
        self.label.setText(_translate("Dialog", "Username:"))
        self.SubmitButton.setText(_translate("Dialog", "Submit"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("Dialog", "Login"))
        self.label_6.setText(_translate("Dialog", "Create a new login user"))
        self.label_3.setText(_translate("Dialog", "Enter a username:"))
        self.label_5.setText(_translate("Dialog", "Confirm password:"))
        self.label_4.setText(_translate("Dialog", "Enter a password:"))
        self.label_8.setText(_translate("Dialog", "ADMIN PASSWORD:"))
        self.AddButton.setText(_translate("Dialog", "Add"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("Dialog", "Add user"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
